displayName=OphidiaVenom Sounds
author=HonestlyGroovy
support=https://github.com/honestlygroovy/ophidia-venom-sounds
description=Ophidiavenom announces when you complete an achievement
tags=ophidiavenom,youtube,completed,sound,twitch,streamer
plugins=com.github.honestlygroovy.ophidiavenom.OphidiavenomPlugin
build=standard