displayName=Ophidiavenom Sounds
author=DapperMickie
support=https://github.com/DapperMickie/ophidiavenom-sounds
description=Ophidiavenom announces when you complete an achievement
tags=ophidiavenom,youtube,completed,sound,kick,twitch,streamer
plugins=com.github.honestlygroovy.ophidiavenom.OphidiavenomPlugin
build=standard